// Generated by https://quicktype.io
import 'dart:convert';

class Cast {
  int id;
  List<CastElement> cast;
  // List<CastElement> crew;

  Cast({
    this.id,
    this.cast,
    // this.crew,
  });
}

class CastElement {
  // bool adult;
  // int gender;
  int id;
  // String knownForDepartment;
  String name;
  String originalName;
  // double popularity;
  String profilePath;
  // int castId;
  // String character;
  // String creditId;
  // int order;

  factory CastElement.fromJSON(Map<String, dynamic> map){
    return CastElement(
      id: map['id'],
      name: map['name'],
      originalName: map['original_name'],
      profilePath: map['profile_path']
    );
  }

  CastElement({
    // this.adult,
    // this.gender,
    this.id,
    // this.knownForDepartment,
    this.name,
    this.originalName,
    // this.popularity,
    this.profilePath,
    // this.castId,
    // this.character,
    // this.creditId,
    // this.order
  });

  Map<String, dynamic> toJSON(){
    return {
      "id": id,
      "name": name,
      "originalName": originalName,
      "profilePath": profilePath
    };
  }

  String resultToJSON(){
    final mapResult = this.toJSON();
    return json.encode(mapResult);
  }
}
