// Generated by https://quicktype.io

class Details {
  String backdropPath;
  List<Genre> genres;
  String homepage;
  int id;
  String originalTitle;
  String overview;
  double popularity;
  String posterPath;
  String releaseDate;
  int runtime;
  String title;
  bool video;
  double voteAverage;
  int voteCount;

  Details({
    this.backdropPath,
    this.genres,
    this.homepage,
    this.id,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.runtime,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
  });
}

class Genre {
  int id;
  String name;

  Genre({
    this.id,
    this.name,
  });
}

class ProductionCompany {
  int id;
  dynamic logoPath;
  String name;
  String originCountry;

  ProductionCompany({
    this.id,
    this.logoPath,
    this.name,
    this.originCountry,
  });
}

class ProductionCountry {
  String iso31661;
  String name;

  ProductionCountry({
    this.iso31661,
    this.name,
  });
}

class SpokenLanguage {
  String englishName;
  String iso6391;
  String name;

  SpokenLanguage({
    this.englishName,
    this.iso6391,
    this.name,
  });
}
