// Generated by https://quicktype.io
import 'dart:convert';

class VideoMovie {
  int id;
  List<ResultMovie> results;

  VideoMovie({
    this.id,
    this.results,
  });
}

class ResultMovie {
  String id;
  // String iso6391;
  // String iso31661;
  String key;
  String name;
  // String site;
  // int size;
  // String type;

  factory ResultMovie.fromJSON(Map<String, dynamic> map){
    return ResultMovie(
      id: map['id'],
      key: map['key'],
      name: map['name']
    );
  }

  ResultMovie({
    this.id,
    // this.iso6391,
    // this.iso31661,
    this.key,
    this.name,
    // this.site,
    // this.size,
    // this.type,
  });

  Map<String, dynamic> toJSON(){
    return {
      "id": id,
      "key": key,
      "name": name
    };
  }

  String resultToJSON(){
    final mapResult = this.toJSON();
    return json.encode(mapResult);
  }
}
