// Generated by https://quicktype.io
import 'dart:convert';

class Trending {
  int page;
  int totalResults;
  int totalPages;
  List<Result> results;

  Trending({
    this.page,
    this.totalResults,
    this.totalPages,
    this.results,
  });
}

class Result {
  int id;
  double popularity;
  int voteCount;
  // bool video;
  String posterPath;
  String backdropPath;
  String title;
  double voteAverage;
  String overview;
  String releaseDate;
  
  // Result({this.popularity, this.voteCount, this.video, this.posterPath, this.id, this.backdropPath, this.title, this.voteAverage, this.overview, this.releaseDate});
  factory Result.fromJSON(Map<String, dynamic> map){
    return Result(
      id: map['id'],
      popularity: map['popularity'],
      voteCount: map['vote_count'],
      posterPath: map['poster_path'],
      backdropPath: map['backdrop_path'],
      title: map['title'],
      voteAverage: map['vote_average'] is int ? (map['vote_average'] as int).toDouble() : map['vote_average'],
      overview: map['overview'],
      releaseDate: map['release_date']
    );
  }

  factory Result.fromJSONDB(Map<String, dynamic> map){
    return Result(
      id: map['id'],
      popularity: map['popularity'],
      voteCount: map['voteCount'],
      posterPath: map['posterPath'],
      backdropPath: map['backdropPath'],
      title: map['title'],
      voteAverage: map['voteAverage'] is int ? (map['voteAverage'] as int).toDouble() : map['voteAverage'],
      overview: map['overview'],
      releaseDate: map['releaseDate']
    );
  }

  Result({
    this.id,
    this.popularity,
    this.voteCount,
    this.posterPath,
    this.backdropPath,
    this.title,
    this.voteAverage,
    this.overview,
    this.releaseDate,
  });

  Map<String, dynamic> toJSON(){
    return {
      "id": id,
      "popularity": popularity,
      "voteCount": voteCount,
      "posterPath": posterPath,
      "backdropPath": backdropPath,
      "title": title,
      "voteAverage": voteAverage,
      "overview": overview,
      "releaseDate": releaseDate
    };
  }

  String resultToJSON(){
    final mapResult = this.toJSON();
    return json.encode(mapResult);
  }
}

enum OriginalLanguage { EN, JA, FR, KO }
